.TH "/home/Jay/trs-80/src/cocoa Directory Reference" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaddressing_mode\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaddressing_mode\&.h\fP"
.br
.ti -1c
.RI "file \fBcomputer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcomputer\&.h\fP"
.br
.ti -1c
.RI "file \fBcontext\&.h\fP"
.br
.ti -1c
.RI "file \fBexception\&.h\fP"
.br
.ti -1c
.RI "file \fBexception\&.inl\fP"
.br
.ti -1c
.RI "file \fBfile_context\&.h\fP"
.br
.ti -1c
.RI "file \fBparse_context\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocessor\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessor\&.inl\fP"
.br
.ti -1c
.RI "file \fBprocessor_list\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprocessor_list\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessor_list\&.inl\fP"
.br
.ti -1c
.RI "file \fBsource_line\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsource_line\&.h\fP"
.br
.ti -1c
.RI "file \fBsource_line\&.inl\fP"
.br
.ti -1c
.RI "file \fBtoken_id\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtoken_id\&.h\fP"
.br
.ti -1c
.RI "file \fBtokenize\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtokenize\&.h\fP"
.br
.ti -1c
.RI "file \fBtokenize\&.inl\fP"
.br
.in -1c
