.TH "/home/Jay/trs-80/src/cocoa/addressing_mode.cpp" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa/addressing_mode.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'addressing_mode\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBassembly\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBassembly::operator<<\fP (std::ostream &os, AddressingMode a)"
.br
.RI "Output the symbol name (eg, 'INHERENT') "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
