.TH "algorithms" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> \fB::assembly::Processor\fP \fBenum_cast\fP (size_t i)"
.br
.RI "Convert integer to Processor (throws EnumCastException) "
.ti -1c
.RI "template<> \fB::assembly::Processor\fP \fBenum_cast\fP (size_t i)"
.br
.RI "Convert integer to Processor (throws EnumCastException) "
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<> \fB::assembly::Processor\fP algorithms::enum_cast (size_t i)\fC [inline]\fP"

.PP
Convert integer to Processor (throws EnumCastException) 
.SS "template<> \fB::assembly::Processor\fP algorithms::enum_cast (size_t i)\fC [inline]\fP"

.PP
Convert integer to Processor (throws EnumCastException) 
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
