.TH "assembly::SourceLine::ParserAction" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
assembly::SourceLine::ParserAction \- Defines the action to take in a given state for a given char input\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParserAction\fP (\fBCharType\fP input_char, \fBActionFn\fP action, \fBParserState\fP next_state)"
.br
.RI "Construction for a normal action\&. "
.ti -1c
.RI "\fBParserAction\fP (\fBCharType\fP input_char, const \fBSourceLine\fP &line, \fBErrorType\fP error)"
.br
.RI "Constructor for a parse error\&. "
.ti -1c
.RI "bool \fBinput_type_matches\fP (char ch) const"
.br
.RI "Is the given character handled by this action? "
.ti -1c
.RI "\fBParserState\fP \fBact\fP (char ch) const"
.br
.RI "Perform the action on the given input\&. "
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "using \fBActionFn\fP = std::function< void(char input_char)>"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBCharType\fP \fB_input_type\fP"
.br
.RI "Input handled by this action\&. "
.ti -1c
.RI "\fBActionFn\fP \fB_action\fP"
.br
.RI "Action to perform\&. "
.ti -1c
.RI "\fBParserState\fP \fB_next_state\fP"
.br
.RI "State to transition to\&. "
.ti -1c
.RI "\fBErrorType\fP \fB_error_type\fP"
.br
.RI "Parse error that occurred\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the action to take in a given state for a given char input\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBassembly::SourceLine::ParserAction::ActionFn\fP =  std::function<void(char input_char)>\fC [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "assembly::SourceLine::ParserAction::ParserAction (\fBCharType\fP input_char, \fBActionFn\fP action, \fBParserState\fP next_state)\fC [inline]\fP"

.PP
Construction for a normal action\&. Construction for a normal parser action\&. 
.SS "assembly::SourceLine::ParserAction::ParserAction (\fBCharType\fP input_char, const \fBSourceLine\fP & line, \fBErrorType\fP error)\fC [inline]\fP"

.PP
Constructor for a parse error\&. Constructor for a parse error handling action\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBSourceLine::ParserState\fP assembly::SourceLine::ParserAction::act (char ch) const\fC [inline]\fP"

.PP
Perform the action on the given input\&. 
.SS "bool assembly::SourceLine::ParserAction::input_type_matches (char ch) const"

.PP
Is the given character handled by this action? 
.SH "Member Data Documentation"
.PP 
.SS "\fBActionFn\fP assembly::SourceLine::ParserAction::_action\fC [private]\fP"

.PP
Action to perform\&. 
.SS "\fBErrorType\fP assembly::SourceLine::ParserAction::_error_type\fC [private]\fP"

.PP
Parse error that occurred\&. 
.SS "\fBCharType\fP assembly::SourceLine::ParserAction::_input_type\fC [private]\fP"

.PP
Input handled by this action\&. 
.SS "\fBParserState\fP assembly::SourceLine::ParserAction::_next_state\fC [private]\fP"

.PP
State to transition to\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
