.TH "assembly::FileContext" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
assembly::FileContext \- Holds information about the current file being parsed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <file_context\&.h>\fP
.PP
Inherits \fBassembly::Context\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Holds information about the current file being parsed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
