.TH "/home/Jay/trs-80/src/cocoa/computer.h" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa/computer.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <iosfwd>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBassembly\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBassembly::Computer\fP : uint8_t { \fBassembly::COCO_2\fP, \fBassembly::COCO_3\fP, \fBassembly::NUM_VALUES\fP }"
.br
.RI "Enumerates the different TRS-80 computers supported\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBassembly::operator<<\fP (std::ostream &os, Computer c)"
.br
.RI "Output as the symbol name, eg 'COCO_2'\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
