.TH "/home/Jay/trs-80/src/cocoa/exception.inl" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa/exception.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBassembly\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename DerivedExceptionType , typename\&.\&.\&. Args> void \fBassembly::throw_\fP (Args &&\&.\&.\&. args)"
.br
.RI "Construct the DerivedExceptionType from the given arguments and throw the exception\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
