.TH "/home/Jay/trs-80/src/cocoa/file_context.h" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa/file_context.h
.SH SYNOPSIS
.br
.PP
\fC#include 'context\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBassembly::FileContext\fP"
.br
.RI "Holds information about the current file being parsed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBassembly\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
