.TH "/home/Jay/trs-80/src/cocoa/tokenize.h" 3 "Sat Aug 20 2022" "CoCoA: TRS-80 Color Computer Assembler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/cocoa/tokenize.h
.SH SYNOPSIS
.br
.PP
\fC#include 'token_id\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <string_view>\fP
.br
\fC#include 'tokenize\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBassembly::Token\fP"
.br
.RI "Information about a recognized token\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBassembly\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Token \fBassembly::recognize_token\fP (std::string_view input_text)"
.br
.RI "Recognize the first token in the input_text\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoCoA: TRS-80 Color Computer Assembler from the source code\&.
