.TH "anonymous_namespace{test_for_each.cpp}" 3 "Sat Aug 20 2022" "Algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
anonymous_namespace{test_for_each.cpp}
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBchar_or_to_string\fP (int x)"
.br
.ti -1c
.RI "std::string \fBchar_or_to_string\fP (char c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string anonymous_namespace{test_for_each\&.cpp}::char_or_to_string (char c)"

.SS "std::string anonymous_namespace{test_for_each\&.cpp}::char_or_to_string (int x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Algorithms from the source code\&.
