.TH "/home/Jay/trs-80/src/common/algorithms/enum_cast.inl" 3 "Sat Aug 20 2022" "Algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/algorithms/enum_cast.inl
.SH SYNOPSIS
.br
.PP
\fC#include 'common/demangle\&.h'\fP
.br
\fC#include 'common/format/format_as_int\&.h'\fP
.br
\fC#include 'c_str\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalgorithms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename ValueType > void \fBalgorithms::throw_enum_cast_exception\fP (ValueType value, const char *optional_error_text)"
.br
.RI "Function used to throw an \fBEnumCastException\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Algorithms from the source code\&.
