.TH "/home/Jay/trs-80/src/common/algorithms/for_each.inl" 3 "Sat Aug 20 2022" "Algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/algorithms/for_each.inl
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalgorithms\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. ValueTypes, typename UnaryFn > void \fBalgorithms::for_each\fP (UnaryFn &&fn, ValueTypes\&.\&.\&. values)"
.br
.RI "Invokes fn(x) once for each x in [values]\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Algorithms from the source code\&.
