.TH "/home/Jay/trs-80/src/common/algorithms/test/test_for_each.cpp" 3 "Sat Aug 20 2022" "Algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/algorithms/test/test_for_each.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./for_each\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBanonymous_namespace{test_for_each\&.cpp}\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBanonymous_namespace{test_for_each\&.cpp}::char_or_to_string\fP (int x)"
.br
.ti -1c
.RI "std::string \fBanonymous_namespace{test_for_each\&.cpp}::char_or_to_string\fP (char c)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Algorithms from the source code\&.
