.TH "/home/Jay/trs-80/src/common/format/format_as_int.inl" 3 "Sat Aug 20 2022" "Text formatting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format/format_as_int.inl
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBformat\fP"
.br
.ti -1c
.RI "namespace \fBformat::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBformat::detail::_format_int\fP (std::string value, char optional_prepend_char)"
.br
.RI "Applies the format spec to the int already converted\&. "
.ti -1c
.RI "template<typename FmtSpec , typename T > std::string \fBformat::detail::format_int_helper\fP (T value)"
.br
.RI "Helper to avoid a lot of code duplication below\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (uint8_t value)"
.br
.RI "Format an 8-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (int8_t value)"
.br
.RI "Format an 8-bit signed value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (uint16_t value)"
.br
.RI "Format a 16-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (int16_t value)"
.br
.RI "Format a 16-bit signed value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (uint32_t value)"
.br
.RI "Format a 32-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (int32_t value)"
.br
.RI "Format a 32-bit signed value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (uint64_t value)"
.br
.RI "Format a 64-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultIntFormatTraits> std::string \fBformat::format_as_int\fP (int64_t value)"
.br
.RI "Format a 64-bit signed value\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Text formatting from the source code\&.
