.TH "/home/Jay/trs-80/src/common/format/test/test_format_as_octal.cpp" 3 "Sat Aug 20 2022" "Text formatting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format/test/test_format_as_octal.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'common/format/format_as_octal\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTest2Traits< PrefixValue >\fP"
.br
.ti -1c
.RI "struct \fBTest3Traits< NumDigits >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Text formatting from the source code\&.
