.TH "/home/Jay/trs-80/src/common/algorithms Directory Reference" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/algorithms Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBc_str\&.h\fP"
.br
.ti -1c
.RI "file \fBc_str\&.inl\fP"
.br
.ti -1c
.RI "file \fBenum_cast\&.cpp\fP"
.br
.ti -1c
.RI "file \fBenum_cast\&.h\fP"
.br
.ti -1c
.RI "file \fBenum_cast\&.inl\fP"
.br
.ti -1c
.RI "file \fBfor_each\&.h\fP"
.br
.ti -1c
.RI "file \fBfor_each\&.inl\fP"
.br
.in -1c
