.TH "/home/Jay/trs-80/src/common/format Directory Reference" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcharacter_case\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcharacter_case\&.h\fP"
.br
.ti -1c
.RI "file \fBcharacter_case\&.inl\fP"
.br
.ti -1c
.RI "file \fBformat_as_binary\&.cpp\fP"
.br
.ti -1c
.RI "file \fBformat_as_binary\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_as_binary\&.inl\fP"
.br
.ti -1c
.RI "file \fBformat_as_enum_and_value\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_as_hex\&.cpp\fP"
.br
.ti -1c
.RI "file \fBformat_as_hex\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_as_hex\&.inl\fP"
.br
.ti -1c
.RI "file \fBformat_as_int\&.cpp\fP"
.br
.ti -1c
.RI "file \fBformat_as_int\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_as_int\&.inl\fP"
.br
.ti -1c
.RI "file \fBformat_as_octal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBformat_as_octal\&.h\fP"
.br
.ti -1c
.RI "file \fBformat_as_octal\&.inl\fP"
.br
.ti -1c
.RI "file \fBjustification\&.cpp\fP"
.br
.ti -1c
.RI "file \fBjustification\&.h\fP"
.br
.ti -1c
.RI "file \fBjustification\&.inl\fP"
.br
.in -1c
