.TH "/home/Jay/trs-80/src/common/algorithms/test Directory Reference" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/algorithms/test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtest_for_each\&.cpp\fP"
.br
.in -1c
