.TH "/home/Jay/trs-80/src/common/format/character_case.cpp" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format/character_case.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'character_case\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <cctype>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBformat\fP"
.br
.ti -1c
.RI "namespace \fBformat::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBformat::detail::_format_chars\fP (std::string text, CharCase char_case)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
