.TH "/home/Jay/trs-80/src/common/demangle.inl" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/demangle.inl
.SH SYNOPSIS
.br
.PP
\fC#include <cxxabi\&.h>\fP
.br
\fC#include <typeinfo>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.ti -1c
.RI "namespace \fBcommon::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBcommon::detail::do_demangle\fP (const std::string &type_id_name)"
.br
.RI "Does the actual work of demangling a typeid(T)\&.name() "
.ti -1c
.RI "template<typename T > std::string \fBcommon::demangle\fP ()"
.br
.RI "Return a string representing the demangled name of a type\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
