.TH "/home/Jay/trs-80/src/common/demangle.h" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/demangle.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'demangle\&.inl'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::string \fBcommon::demangle\fP ()"
.br
.RI "Return a string representing the demangled name of a type\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
