.TH "/home/Jay/trs-80/src/common/format/format_as_octal.h" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format/format_as_octal.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'format_as_octal\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBformat::DefaultOctalFormatTraits\fP"
.br
.RI "Default formatting for octal values\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBformat\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBformat::OctalPrefix\fP : uint8_t { \fBformat::PREFIX_NONE\fP, \fBformat::LEADING_ZERO\fP }"
.br
.RI "What should be added to the front of the value to\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename FmtSpec  = DefaultOctalFormatTraits> std::string \fBformat::format_as_octal\fP (uint8_t value)"
.br
.RI "Format an 8-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultOctalFormatTraits> std::string \fBformat::format_as_octal\fP (uint16_t value)"
.br
.RI "Format a 16-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultOctalFormatTraits> std::string \fBformat::format_as_octal\fP (uint32_t value)"
.br
.RI "Format a 32-bit unsigned value\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultOctalFormatTraits> std::string \fBformat::format_as_octal\fP (uint64_t value)"
.br
.RI "Format a 64-bit unsigned value\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
