.TH "/home/Jay/trs-80/src/common/format/format_as_binary.inl" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/Jay/trs-80/src/common/format/format_as_binary.inl
.SH SYNOPSIS
.br
.PP
\fC#include <bitset>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBformat\fP"
.br
.ti -1c
.RI "namespace \fBformat::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBformat::detail::_format_binary\fP (std::string value, BinaryPrefix prefix)"
.br
.RI "Applies the format spec to the int already converted\&. "
.ti -1c
.RI "template<typename FmtSpec , typename T > std::string \fBformat::detail::format_binary_helper\fP (T value)"
.br
.RI "Helper to avoid a lot of code duplication below\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (uint8_t value)"
.br
.RI "Format an 8-bit unsigned value to 8-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (int8_t value)"
.br
.RI "Format an 8-bit signed value to 8-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (uint16_t value)"
.br
.RI "Format a 16-bit unsigned value to 16-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (int16_t value)"
.br
.RI "Format a 16-bit signed value to 16-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (uint32_t value)"
.br
.RI "Format a 32-bit unsigned value to 32-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (int32_t value)"
.br
.RI "Format a 32-bit signed value to 32-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (uint64_t value)"
.br
.RI "Format a 64-bit unsigned value to 64-char string\&. "
.ti -1c
.RI "template<typename FmtSpec  = DefaultBinaryFormatTraits> std::string \fBformat::format_as_binary\fP (int64_t value)"
.br
.RI "Format a 64-bit signed value to 64-char string\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
