.TH "Test7Traits" 3 "Sat Aug 20 2022" "Common code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test7Traits
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformat::DefaultJustificationTraits\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBFieldWidth\fP = 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "constexpr size_t Test7Traits::FieldWidth = 1\fC [static]\fP, \fC [constexpr]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Common code from the source code\&.
